# Generated by Django 3.1.6 on 2021-02-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.FilePathField(path='/plants/img'),
        ),
    ]
