# Generated by Django 3.1.6 on 2021-02-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20210209_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
